### ISSUE TITLE
ThrottlingException

### ISSUE THREAD

**Issue by viralpatel94** [awslabs/workspaces-cost-optimizer#11]
I am getting the below traceback, the solution is running on environment of about 160 instances and on instance 86 is where this error occurs.

`Traceback (most recent call last):
File "./wco.py", line 145, in <module>
countWorkspaces = directoryReader.read_directory(wsRegion, stackParams, directoryParams)
File "/app/lib/directory_reader.py", line 113, in read_directory
result = workspacesHelper.process_workspace(workspace)
File "/app/lib/workspaces_helper.py", line 94, in process_workspace
workspaceBundleType = self.get_bundle_type(workspace)
File "/app/lib/workspaces_helper.py", line 136, in get_bundle_type
BundleIds = [workspace['BundleId']]
File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 357, in _api_call
return self._make_api_call(operation_name, kwargs)
File "/usr/local/lib/python3.7/site-packages/botocore/client.py", line 661, in _make_api_call
raise error_class(parsed_response, operation_name)
botocore.exceptions.ClientError: An error occurred (ThrottlingException) when calling the DescribeWorkspaceBundles operation (reached max retries: 4): Rate exceeded
`

In the workspaces_helper.py I have tried using botoConfig to add more retries like below: 

`botoConfig = botocore.config.Config(
    max_pool_connections=100,
    retries = dict(max_attempts = 20)
)` 

and changing the `time.sleep(i)`

**Comment by viralpatel94** [comment]
I changed the time.sleep through out the .py scripts to time.sleep(i) and changed the maxRetries to 7 in wco.py and kept it at 20 in other .py files. Currently not running into rate throttling errors.
